jazzy.gz-common-vendor: Add missing include
This is needed to fix build of gz-sim-vendor:

In file included from /build/gz_sim_vendor-release-release-jazzy-gz_sim_vendor-0.0.10-1/build/gz_sim_vendor-prefix/src/gz_sim_vendor/src/systems/battery_plugin/LinearBatteryPlugin.hh:25,
                 from /build/gz_sim_vendor-release-release-jazzy-gz_sim_vendor-0.0.10-1/build/gz_sim_vendor-prefix/src/gz_sim_vendor/src/systems/battery_plugin/LinearBatteryPlugin.cc:18:
/nix/store/2lzh9i957jbzjfv6pbf9wxsp0gx5b0q7-ros-jazzy-gz-common-vendor-0.0.9-r1/include/gz/common5/gz/common/Battery.hh:47:32: error: 'uint32_t' was not declared in this scope
   47 |       public: typedef std::map<uint32_t, double> PowerLoad_M;
      |                                ^~~~~~~~